# Generated by Django 3.0.5 on 2020-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='raw_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_id',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
