# Generated by Django 3.0.5 on 2020-04-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0002_auto_20200430_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created',
        ),
    ]
