# Generated by Django 3.0.5 on 2020-04-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0004_remove_message_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.IntegerField(default=0),
        ),
    ]
