# Generated by Django 3.0.5 on 2020-04-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200424_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='raw_message',
            field=models.TextField(default='', verbose_name='raw_message'),
        ),
    ]
